[package]
name = "tma-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6", features = ["cors"] }
hmac = "0.12"
sha2 = "0.10"
hex = "0.4"
tower = "0.5"
urlencoding = "2"
lazy_static = "1.5"
ahash = "0.8"
url = "2.5"
bb8 = "0.9"
bb8-redis = "0.18"
redis = { version = "0.27", features = ["tokio-comp", "tokio-native-tls-comp"] }
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.11" }
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.11" }
