[package]
name = "tma-rust"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = true
debug = false

[dependencies]
axum = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6", features = ["cors"] }
hmac = "0.12"
sha2 = "0.10"
hex = "0.4"
tower = { version = "0.5", features = ["limit", "buffer", "timeout"] }
urlencoding = "2"
lazy_static = "1.5"
ahash = "0.8"
url = "2.5"
bb8 = "0.9"
bb8-redis = "0.18"
redis = { version = "0.27", features = ["tokio-comp", "tokio-native-tls-comp"] }
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.11" }
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.11" }
tracing-subscriber = "0.3.19"
num_cpus = "1.16.0"
tracing = "0.1.41"
